export const baseUrl = "http://localhost:3000";


export const defaultRecipes = [
    {
    _id: 0,
    name: "Apple Crumble Cheesecake",
    ingredients: ["For the Crust:", "3 cups of Graham Cracker Crumbs", "8 tablespoons of Butter, melter (one stick)", "For the Cheeseccake:","24 ounces of Cream Cheese, softened (3 bricks)", "1/2 cup of Granulated Sugar", "1/2 cup of Sour Cream", "1/2 cup of Caramel Sauce", "2 tablespoons of All-Purpose Flour", "1 teaspoon of Vanilla Extract (DO NOT USE FLAVORING)", "3 Eggs", "For the Apple Crumble:", "2 cups of Diced Apples", "2 tablespoons of Granulated Sugar", "2 teaspoons of Cornstarch", "1 teaspoon of Cinnamon", "1/2 cup of All-Purpose Flour", "1/2 cup of Brown Sugar", "1/2 cup of Rolled Oats", "4 tablespoons of Butter, melted" ],
    instructions: "For the Crust: Preheat the oven to 350 degrees F and grease a 9” springform pan with nonstick baking spray. In a medium bowl, mix together the graham cracker crumbs and melted butter. Transfer the mixture to the prepared pan and press it into an even layer on the bottom and 1” up the sides. Bake the crust for 10 minutes. Then set it aside. For the Cheesecake Layer: Add the softened cream cheese and sugar to the bowl of a stand mixer fitted with the paddle attachment. Beat on medium speed until well combined, about 2 minutes. Next, add the sour cream, caramel sauce, flour, and vanilla. Mix them to combine. With the mixer on low speed, add the eggs one at a time. Mix it just until the eggs are fully combined. Carefully pour the cheesecake on top of the crust and set it aside. For the Apple Crumble: In a medium bowl, mix together the apple, granulated sugar, cornstarch, and cinnamon. Spread the apple mixture on top of the cheesecake. In another small bowl, mix together the flour, brown sugar, and oats. Add the melted butter and mix until clumps begin to form. Sprinkle the crumble evenly over the apples. Bake the cheesecake for 55-60 minutes, or until the center no longer jiggles when shaken. When the cheesecake is set, turn off the oven and open the door– but leave the cheesecake in the oven. Allow it to cool to room temperature– about 2 hours. Transfer the cheesecake to the fridge and chill until set– at least 4 hours, but preferably overnight.",
    imageUrl: "https://www.everydayfamilycooking.com/wp-content/uploads/2022/09/apple-crumble-cheesecake-2-768x1152.jpg",
    }
]